import { ITEM_SCHEMA as schema, type DifferentialCase } from '../harness.js';

export const cases: DifferentialCase[] = [
    { name: 'ROUND of 2.5 is 3 (half away from zero)', schema, record: { id: 1, x: '2.5' }, expr: 'ROUND(.x)', expect: '3' },
    { name: 'ROUND of -2.5 is -3 (half away from zero)', schema, record: { id: 1, x: '-2.5' }, expr: 'ROUND(.x)', expect: '-3' },
    { name: 'ROUND of 0.5 is 1', schema, record: { id: 1, x: '0.5' }, expr: 'ROUND(.x)', expect: '1' },
    { name: 'ROUND of -0.5 is -1', schema, record: { id: 1, x: '-0.5' }, expr: 'ROUND(.x)', expect: '-1' },
    { name: 'ROUND of 2.4 is 2', schema, record: { id: 1, x: '2.4' }, expr: 'ROUND(.x)', expect: '2' },
    { name: 'ROUND of -2.6 is -3', schema, record: { id: 1, x: '-2.6' }, expr: 'ROUND(.x)', expect: '-3' },
    { name: 'ROUND of 1.005 to 2 digits is 1.01 (exact decimal)', schema, record: { id: 1, x: '1.005' }, expr: 'ROUND(.x, 2)', expect: '1.01' },
    { name: 'ROUND of -1.005 to 2 digits is -1.01', schema, record: { id: 1, x: '-1.005' }, expr: 'ROUND(.x, 2)', expect: '-1.01' },
    { name: 'ROUND with more digits than the value has', schema, record: { id: 1, x: '1.5' }, expr: 'ROUND(.x, 3)', expect: '1.5' },
    { name: 'ROUND with a negative digits count', schema, record: { id: 1, x: '1250.5' }, expr: 'ROUND(.x, -2)', expect: '1300' },
    { name: 'ROUND of an INTEGER is the same INTEGER', schema, record: { id: 1, a: 7 }, expr: 'ROUND(.a)', expect: 7 },
    { name: 'ROUND of an INTEGER with a negative digits count', schema, record: { id: 1, a: 15 }, expr: 'ROUND(.a, -1)', expect: 20 },
    { name: 'ROUND of a negative INTEGER with a negative digits count', schema, record: { id: 1, a: -15 }, expr: 'ROUND(.a, -1)', expect: -20 },
    { name: 'ROUND of null is null', schema, record: { id: 1, n: null }, expr: 'ROUND(.n)', expect: null },
    { name: 'ROUND with null digits is null', schema, record: { id: 1, x: '1.5', n: null }, expr: 'ROUND(.x, .n)', expect: null },
    { name: 'ROUND a price with tax', schema, record: { id: 1, x: '19.99', y: '1.09' }, expr: 'ROUND(.x * .y, 2)', expect: '21.79' },
    { name: 'ABS of a negative INTEGER', schema, record: { id: 1, a: -4 }, expr: 'ABS(.a)', expect: 4 },
    { name: 'ABS of a positive INTEGER', schema, record: { id: 1, a: 4 }, expr: 'ABS(.a)', expect: 4 },
    { name: 'ABS of 0', schema, record: { id: 1, a: 0 }, expr: 'ABS(.a)', expect: 0 },
    { name: 'ABS of a negative DECIMAL', schema, record: { id: 1, x: '-2.50' }, expr: 'ABS(.x)', expect: '2.5' },
    { name: 'ABS of null is null', schema, record: { id: 1, n: null }, expr: 'ABS(.n)', expect: null },
    { name: 'FLOOR of a positive DECIMAL', schema, record: { id: 1, x: '2.7' }, expr: 'FLOOR(.x)', expect: 2 },
    { name: 'FLOOR of a negative DECIMAL goes down', schema, record: { id: 1, x: '-2.1' }, expr: 'FLOOR(.x)', expect: -3 },
    { name: 'FLOOR of a whole DECIMAL', schema, record: { id: 1, x: '-2.0' }, expr: 'FLOOR(.x)', expect: -2 },
    { name: 'FLOOR of an INTEGER', schema, record: { id: 1, a: 5 }, expr: 'FLOOR(.a)', expect: 5 },
    { name: 'FLOOR of null is null', schema, record: { id: 1, n: null }, expr: 'FLOOR(.n)', expect: null },
    { name: 'CEIL of a positive DECIMAL', schema, record: { id: 1, x: '2.1' }, expr: 'CEIL(.x)', expect: 3 },
    { name: 'CEIL of a negative DECIMAL goes up', schema, record: { id: 1, x: '-2.7' }, expr: 'CEIL(.x)', expect: -2 },
    { name: 'CEIL of a whole DECIMAL', schema, record: { id: 1, x: '2.0' }, expr: 'CEIL(.x)', expect: 2 },
    { name: 'CEIL of an INTEGER', schema, record: { id: 1, a: -5 }, expr: 'CEIL(.a)', expect: -5 },
    { name: 'CEIL of null is null', schema, record: { id: 1, n: null }, expr: 'CEIL(.n)', expect: null }
];
