import { ITEM_SCHEMA as schema, type DifferentialCase } from '../harness.js';

const hello = { id: 1, s: 'Hello World', t: null, ci: 'Hello' };
const padded = { id: 1, s: ' \t\r\n  hi there \n\t ', t: null };
const arabic = { id: 1, s: 'سلام' };
const emoji = { id: 1, s: '😀' };
const percent = { id: 1, s: '50%', t: 'a_c' };

export const cases: DifferentialCase[] = [
    { name: 'LOWER', schema, record: hello, expr: 'LOWER(.s)', expect: 'hello world' },
    { name: 'UPPER', schema, record: hello, expr: 'UPPER(.s)', expect: 'HELLO WORLD' },
    { name: 'LOWER of null is null', schema, record: hello, expr: 'LOWER(.t)', expect: null },
    { name: 'UPPER of empty text', schema, record: { id: 1, s: '' }, expr: 'UPPER(.s)', expect: '' },
    { name: 'UPPER keeps letters without case (Persian)', schema, record: arabic, expr: 'UPPER(.s)', expect: 'سلام' },
    { name: 'UPPER maps accented letters', schema, record: { id: 1, s: 'école' }, expr: 'UPPER(.s)', expect: 'ÉCOLE' },
    { name: 'LOWER maps accented letters', schema, record: { id: 1, s: 'ÉCOLE' }, expr: 'LOWER(.s)', expect: 'école' },
    { name: 'STARTS_WITH ignores case of accented letters for CITEXT', schema, record: { id: 1, ci: 'École' }, expr: 'STARTS_WITH(.ci, "éc")', expect: true },
    { name: 'TRIM removes spaces, tabs and line breaks', schema, record: padded, expr: 'TRIM(.s)', expect: 'hi there' },
    { name: 'TRIM of null is null', schema, record: padded, expr: 'TRIM(.t)', expect: null },
    { name: 'TRIM of empty text', schema, record: { id: 1, s: '' }, expr: 'TRIM(.s)', expect: '' },
    { name: 'LENGTH of text', schema, record: hello, expr: 'LENGTH(.s)', expect: 11 },
    { name: 'LENGTH of empty text is 0', schema, record: { id: 1, s: '' }, expr: 'LENGTH(.s)', expect: 0 },
    { name: 'LENGTH of null is null', schema, record: hello, expr: 'LENGTH(.t)', expect: null },
    { name: 'LENGTH counts code points: one emoji is 1', schema, record: emoji, expr: 'LENGTH(.s)', expect: 1 },
    { name: 'LENGTH counts code points: Persian text is 4', schema, record: arabic, expr: 'LENGTH(.s)', expect: 4 },
    { name: 'SUBSTRING with start and length', schema, record: hello, expr: 'SUBSTRING(.s, 2, 3)', expect: 'ell' },
    { name: 'SUBSTRING without length reads to the end', schema, record: hello, expr: 'SUBSTRING(.s, 7)', expect: 'World' },
    { name: 'SUBSTRING start before 1 cuts the length', schema, record: hello, expr: 'SUBSTRING(.s, 0, 3)', expect: 'He' },
    { name: 'SUBSTRING start below 1 without length gives all', schema, record: hello, expr: 'SUBSTRING(.s, -5)', expect: 'Hello World' },
    { name: 'SUBSTRING past the end is empty', schema, record: hello, expr: 'SUBSTRING(.s, 50, 3)', expect: '' },
    { name: 'SUBSTRING with length 0 is empty', schema, record: hello, expr: 'SUBSTRING(.s, 2, 0)', expect: '' },
    { name: 'SUBSTRING with a negative length is an error', schema, record: hello, expr: 'SUBSTRING(.s, 2, -1)', expect: { error: 'other' } },
    { name: 'SUBSTRING counts code points (Persian)', schema, record: arabic, expr: 'SUBSTRING(.s, 2, 2)', expect: 'لا' },
    { name: 'SUBSTRING counts code points (emoji)', schema, record: { id: 1, s: 'a😀b' }, expr: 'SUBSTRING(.s, 2, 1)', expect: '😀' },
    { name: 'SUBSTRING of null is null', schema, record: hello, expr: 'SUBSTRING(.t, 1, 2)', expect: null },
    { name: 'SUBSTRING with a null start is null', schema, record: { id: 1, s: 'abc', n: null }, expr: 'SUBSTRING(.s, .n)', expect: null },
    { name: 'REPLACE changes every match', schema, record: { id: 1, s: 'a-b-c', t: '-' }, expr: 'REPLACE(.s, .t, "+")', expect: 'a+b+c' },
    { name: 'REPLACE does not read % as a wildcard', schema, record: percent, expr: 'REPLACE(.s, "%", "!")', expect: '50!' },
    { name: 'REPLACE with an empty search text changes nothing', schema, record: hello, expr: 'REPLACE(.s, "", "x")', expect: 'Hello World' },
    { name: 'REPLACE with null is null', schema, record: hello, expr: 'REPLACE(.s, .t, "x")', expect: null },
    { name: 'REPLACE with Persian text', schema, record: arabic, expr: 'REPLACE(.s, "ل", "x")', expect: 'سxام' },
    { name: 'STARTS_WITH is true', schema, record: hello, expr: 'STARTS_WITH(.s, "Hello")', expect: true },
    { name: 'STARTS_WITH is case sensitive for TEXT', schema, record: hello, expr: 'STARTS_WITH(.s, "hello")', expect: false },
    { name: 'STARTS_WITH ignores case for CITEXT', schema, record: hello, expr: 'STARTS_WITH(.ci, "HEL")', expect: true },
    { name: 'STARTS_WITH ignores case when the other side is CITEXT', schema, record: hello, expr: 'STARTS_WITH(.s, .ci)', expect: true },
    { name: 'STARTS_WITH with an empty part is true', schema, record: hello, expr: 'STARTS_WITH(.s, "")', expect: true },
    { name: 'STARTS_WITH with null is null', schema, record: hello, expr: 'STARTS_WITH(.t, "a")', expect: null },
    { name: 'STARTS_WITH does not read _ as a wildcard', schema, record: percent, expr: 'STARTS_WITH(.t, "a_")', expect: true },
    { name: 'STARTS_WITH does not read % as a wildcard', schema, record: percent, expr: 'STARTS_WITH(.s, "%")', expect: false },
    { name: 'ENDS_WITH is true', schema, record: hello, expr: 'ENDS_WITH(.s, "World")', expect: true },
    { name: 'ENDS_WITH is case sensitive for TEXT', schema, record: hello, expr: 'ENDS_WITH(.s, "world")', expect: false },
    { name: 'ENDS_WITH ignores case for CITEXT', schema, record: hello, expr: 'ENDS_WITH(.ci, "LLO")', expect: true },
    { name: 'ENDS_WITH with an empty part is true', schema, record: hello, expr: 'ENDS_WITH(.s, "")', expect: true },
    { name: 'ENDS_WITH with a part longer than the text is false', schema, record: hello, expr: 'ENDS_WITH(.s, "xxxxxxxxxxxxxxxx")', expect: false },
    { name: 'ENDS_WITH does not read % as a wildcard', schema, record: percent, expr: 'ENDS_WITH(.s, "%")', expect: true },
    { name: 'ENDS_WITH % does not match another text', schema, record: hello, expr: 'ENDS_WITH(.s, "%")', expect: false },
    { name: 'ENDS_WITH with null is null', schema, record: hello, expr: 'ENDS_WITH(.t, "a")', expect: null },
    { name: 'CONTAINS finds a part', schema, record: hello, expr: 'CONTAINS(.s, "lo W")', expect: true },
    { name: 'CONTAINS "%" in "50%" is true', schema, record: percent, expr: 'CONTAINS(.s, "%")', expect: true },
    { name: 'CONTAINS "%" in "abc" is false', schema, record: { id: 1, s: 'abc' }, expr: 'CONTAINS(.s, "%")', expect: false },
    { name: 'CONTAINS "_" is not a wildcard', schema, record: { id: 1, s: 'abc' }, expr: 'CONTAINS(.s, "_")', expect: false },
    { name: 'CONTAINS is case sensitive for TEXT', schema, record: hello, expr: 'CONTAINS(.s, "WORLD")', expect: false },
    { name: 'CONTAINS ignores case for CITEXT', schema, record: hello, expr: 'CONTAINS(.ci, "ELL")', expect: true },
    { name: 'CONTAINS with an empty part is true', schema, record: hello, expr: 'CONTAINS(.s, "")', expect: true },
    { name: 'CONTAINS with null is null', schema, record: hello, expr: 'CONTAINS(.s, .t)', expect: null },
    { name: 'CONTAINS finds an emoji', schema, record: { id: 1, s: 'a😀b' }, expr: 'CONTAINS(.s, "😀")', expect: true },
    { name: 'CONTAINS finds Persian text', schema, record: arabic, expr: 'CONTAINS(.s, "لا")', expect: true },
    { name: 'a function inside a function', schema, record: padded, expr: 'LENGTH(TRIM(.s))', expect: 8 }
];
