#!/usr/bin/env node
/**
 * Writes `docs/reference/diagnostics.md`, the list of every diagnostic code,
 * from the registry in `src/language/diagnostics/codes.ts`.
 *
 * Usage (from the repository root, after a build):
 *   npm run docs:diagnostics            write the page
 *   node scripts/diagnostics-doc.mjs --check   exit 1 when the page is out of date
 *
 * The page is generated. Never edit it by hand. `test/diagnostic-codes.test.ts`
 * fails when it is out of date.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const DOC_PATH = resolve(ROOT, 'docs/reference/diagnostics.md');

const AREAS = {
    syntax: 'The text is not a valid program (lexer and parser errors).',
    scope: 'A name, table, column or sigil cannot be found.',
    type: 'A type rule is broken. Minab never converts types by itself (spec §5.5).',
    null: 'A null rule is broken (spec §7.7).',
    call: 'A function call is wrong.',
    compile: 'A program cannot become SQL.',
    query: 'A query is used in a way its shape does not allow.',
    rule: 'A rule cannot be checked in this setting.'
};

/** The message with every parameter shown as `{name}`, and the names of the parameters in order of use. */
function pattern(entry) {
    const names = [];
    const params = new Proxy(
        {},
        {
            get(_target, key) {
                const name = String(key);
                if (!names.includes(name)) names.push(name);
                return `{${name}}`;
            }
        }
    );
    return { text: entry.message(params), names };
}

const cell = text => text.replaceAll('|', '\\|');

/**
 * @param {Record<string, { severity: string, message: (params: any) => string, doc: string }>} diagnostics
 * @returns {string}
 */
export function renderDiagnosticsDoc(diagnostics) {
    const codes = Object.keys(diagnostics).sort();
    const lines = [
        '# Diagnostic codes',
        '',
        '<!-- Generated by `npm run docs:diagnostics` from src/language/diagnostics/codes.ts. Do not edit by hand. -->',
        '',
        'Every diagnostic that the checker makes has a stable code. The message is English. A host can translate it',
        'by its code and fill it with the parameters. The parameters are in `data.params` of the diagnostic',
        '(and in the `diagnostics` list of `minab check --json`). Minab ships no translations.',
        '',
        'Codes have the form `<area>.<name>`. From version 1.0 on, a code never changes its meaning.',
        ''
    ];
    for (const [area, summary] of Object.entries(AREAS)) {
        const inArea = codes.filter(code => code.startsWith(`${area}.`));
        if (inArea.length === 0) continue;
        lines.push(`## ${area}`, '', summary, '', '| Code | Severity | Message | Parameters | What to do |', '| --- | --- | --- | --- | --- |');
        for (const code of inArea) {
            const entry = diagnostics[code];
            const { text, names } = pattern(entry);
            const parameters = names.length === 0 ? 'none' : names.map(name => `\`${name}\``).join(', ');
            lines.push(`| \`${code}\` | ${entry.severity} | ${cell(text)} | ${parameters} | ${cell(entry.doc)} |`);
        }
        lines.push('');
    }
    return lines.join('\n');
}

async function main(argv) {
    const built = resolve(ROOT, 'out/src/language/diagnostics/codes.js');
    if (!existsSync(built)) {
        console.error('Build first: npm run build');
        return 2;
    }
    const { DIAGNOSTICS } = await import(pathToFileURL(built).href);
    const page = renderDiagnosticsDoc(DIAGNOSTICS);
    if (argv.includes('--check')) {
        const current = existsSync(DOC_PATH) ? readFileSync(DOC_PATH, 'utf8') : '';
        if (current !== page) {
            console.error('docs/reference/diagnostics.md is out of date. Run: npm run docs:diagnostics');
            return 1;
        }
        return 0;
    }
    mkdirSync(dirname(DOC_PATH), { recursive: true });
    writeFileSync(DOC_PATH, page);
    console.log(`wrote ${DOC_PATH}`);
    return 0;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
    process.exitCode = await main(process.argv.slice(2));
}
