import type {
    DefaultSharedCoreModuleContext,
    LangiumCoreServices,
    LangiumSharedCoreServices,
    Module,
    PartialLangiumCoreServices
} from 'langium';
import { createDefaultCoreModule, createDefaultSharedCoreModule, inject } from 'langium';
import { MinabGeneratedModule, MinabGeneratedSharedModule } from './generated/module.js';
import { MinabScopeResolver } from './minab-scope-resolver.js';
import { MinabTypeChecker } from './minab-type-checker.js';
import { registerValidationChecks } from './minab-validator.js';
import { DEFAULT_RULE_CONTEXT, EMPTY_SCHEMA, SchemaProvider, type MinabRuleContext, type MinabSchema } from './schema.js';

/**
 * Declaration of custom services for the Minab language.
 *
 *  - `schema`: the host-supplied table/column/function contract (see
 *    `schema.ts`) — Minab has no in-file table declarations, so this is
 *    the only source of truth for what `#alias`/bare table names mean.
 *  - `scopeResolver`: resolves the scope-stack sigils (`.`/`^`/`#alias`/
 *    `KEY`, spec §2.2) plus bare `NameRef` lookups. Not a Langium
 *    `ScopeProvider` — see `minab-scope-resolver.ts` for why.
 *  - `ruleContext`: host-supplied fact about whether the program being
 *    validated is a field-level rule, and (Phase 4) `$`'s type when it is
 *    (see `schema.ts`) — consumed by the `Validator`'s `$`-placement check
 *    and by `typeChecker`.
 *  - `typeChecker`: type inference/checking (Phase 4, `minab-type-
 *    checker.ts`) over the expression grammar — no-implicit-coercion,
 *    the §3.4 collection-vs-scalar boundary, and the §7.7 null-operand
 *    rules, all enforced as validator checks that call `inferType`.
 *
 * The `Validator` (`minab-validator.ts`) checks: `$` only valid when
 * `ruleContext.isFieldRule`; `KEY` only valid after `GROUPBY`; `#alias`
 * referencing an undeclared table (Phase 3); plus the full set of
 * type-checking diagnostics built on `typeChecker` (Phase 4).
 *
 * Note: this module wires only the *core* Langium services (parsing, AST,
 * scoping, validation) — no LSP/IDE services (`langium/lsp`) yet. Add those
 * (and switch to `LangiumServices`/`createDefaultModule` from `langium/lsp`)
 * once a language server / VS Code extension is actually needed.
 */
export type MinabAddedServices = {
    schema: SchemaProvider;
    scopeResolver: MinabScopeResolver;
    ruleContext: MinabRuleContext;
    typeChecker: MinabTypeChecker;
};

/**
 * Union of Langium default core services and Minab-specific services.
 */
export type MinabServices = LangiumCoreServices & MinabAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared custom services. The Langium defaults can be
 * partially specified to override only distinct fields, while the
 * custom services must be fully specified.
 *
 * Takes the host-supplied schema and rule context as parameters (rather
 * than static exports) since both are genuinely per-embedding/per-document
 * data, not project constants.
 */
function createMinabModule(
    schema: MinabSchema,
    ruleContext: MinabRuleContext
): Module<MinabServices, PartialLangiumCoreServices & MinabAddedServices> {
    return {
        schema: () => new SchemaProvider(schema),
        scopeResolver: services => new MinabScopeResolver(services.schema),
        ruleContext: () => ruleContext,
        typeChecker: services => new MinabTypeChecker(services.schema, services.scopeResolver, services.ruleContext)
    };
}

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * `schema` is the host application's table/column/function contract (see
 * `schema.ts`); it defaults to empty for callers (e.g. the parsing smoke
 * suite) that don't need scope/schema resolution. `ruleContext` says
 * whether the program being validated is a field-level rule; it defaults
 * to `false` (record-level/general program).
 */
export function createMinabServices(
    context: DefaultSharedCoreModuleContext,
    schema: MinabSchema = EMPTY_SCHEMA,
    ruleContext: MinabRuleContext = DEFAULT_RULE_CONTEXT
): {
    shared: LangiumSharedCoreServices;
    Minab: MinabServices;
} {
    const shared = inject(
        createDefaultSharedCoreModule(context),
        MinabGeneratedSharedModule
    );
    const Minab = inject(
        createDefaultCoreModule({ shared }),
        MinabGeneratedModule,
        createMinabModule(schema, ruleContext)
    );
    shared.ServiceRegistry.register(Minab);
    registerValidationChecks(Minab);
    return { shared, Minab };
}
