import type {
    DefaultSharedCoreModuleContext,
    LangiumCoreServices,
    LangiumSharedCoreServices,
    Module,
    PartialLangiumCoreServices
} from 'langium';
import { createDefaultCoreModule, createDefaultSharedCoreModule, inject } from 'langium';
import { MinabGeneratedModule, MinabGeneratedSharedModule } from './generated/module.js';

/**
 * Declaration of custom services for the Minab language.
 *
 * This is intentionally empty for now — it's the extension point for the
 * pieces of Minab that go beyond what Langium's defaults provide:
 *
 *  - a custom ScopeProvider, because `@alias` (NamedScope) and `^`
 *    (ParentRecord) resolve against Minab's scope *stack*, not the
 *    lexical/AST-node scoping Langium assumes by default (see spec §2.2)
 *  - a custom Validator for semantic checks (e.g. `$` only valid inside a
 *    `field` rule, `KEY` only valid after `GROUP BY`, relation/traversal
 *    type-checking per §3)
 *
 * Add fields here as those services are implemented, e.g.:
 *   MinabScopeProvider: MinabScopeProvider
 *
 * Note: this module wires only the *core* Langium services (parsing, AST,
 * scoping, validation) — no LSP/IDE services (`langium/lsp`) yet. Add those
 * (and switch to `LangiumServices`/`createDefaultModule` from `langium/lsp`)
 * once a language server / VS Code extension is actually needed.
 */
export type MinabAddedServices = Record<string, never>;

/**
 * Union of Langium default core services and Minab-specific services.
 */
export type MinabServices = LangiumCoreServices & MinabAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared custom services. The Langium defaults can be
 * partially specified to override only distinct fields, while the
 * custom services must be fully specified.
 */
export const MinabModule: Module<MinabServices, PartialLangiumCoreServices & MinabAddedServices> = {
    // Custom service bindings go here as they're implemented.
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createMinabServices(context: DefaultSharedCoreModuleContext): {
    shared: LangiumSharedCoreServices;
    Minab: MinabServices;
} {
    const shared = inject(
        createDefaultSharedCoreModule(context),
        MinabGeneratedSharedModule
    );
    const Minab = inject(
        createDefaultCoreModule({ shared }),
        MinabGeneratedModule,
        MinabModule
    );
    shared.ServiceRegistry.register(Minab);
    return { shared, Minab };
}
